### ISSUE TITLE
Installation instructions should use venv

### ISSUE THREAD

**Issue by vauhochzett** [Neihtq/typefast#15]
I would recomment to use a venv for installation. Changes required would be:

- Add venv as requirement
- Add steps to add & activate virtual environment to installation

See: https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by vauhochzett** [comment]
Alternatively, my preferred way personally is to use pipenv: https://pipenv.pypa.io/en/latest/

Let me know if you want to switch to that!

**Comment by Neihtq** [comment]
I think it's up to the users themselves, whether they want to install the requirements on their system or on the virtual environment of their choice.

Regarding pipenv: I don't like it.

**Comment by vauhochzett** [comment]
Fair. Just out of curiousity: Why do you not like pipenv, except for it maybe being a tad slow?

**Comment by Neihtq** [comment]
i had many occasions were it wasn't a "tad" slow. With every package that (un)installed the locking took forever.
