### ISSUE TITLE
Suggestion: Remove special characters and lowercase all letters

### ISSUE THREAD

**Issue by vauhochzett** [Neihtq/typefast#17]
Currently, quotes can be of arbitrary difficulty due to special characters (mainly punctuation) or capitalization. See, e.g.: 

> The biggest difficulty in film industry today is not that of getting dates, actors_or finance, but_writers. We don't ge
t writers. They are like heart surgeons with whom you need to meet after fixing an appointment.
> 
> -Sajid Khan

I would suggest to remove punctuation etc. and lowercase all letters.

**Comment by Neihtq** [comment]
Uppercase letters and punctuation are part of the English language. In professional/competitive speed typing they also keep the uppercase letters and punctuations.

In other words: git gud, duh!
