### ISSUE TITLE
Received NoneType error when entering backspace

### ISSUE THREAD

**Issue by NiklasRosenstein** [Neihtq/typefast#8]
When I mistype and press backspace, I get the following error:

![image](https://user-images.githubusercontent.com/1318438/186101396-7aa068d6-b500-441d-8705-4616d9d931bd.png)

Also, it would be nice if the error wouldn't be jumbled like this. 🙂

**Comment by Neihtq** [comment]
Could not really reproduce the jumbled stacktrace, hope the pull request will fix this nonetheless
